Add Kamelet module from Beefy-ts
quarkus-qe/quarkus-test-suite pull request #101
Opened 2021-07-21 09:39 UTC by pjgg

2021-07-22 07:23 UTC, Sgitario commented
Pls, rebase the PR.

2021-07-22 07:27 UTC, Sgitario commented
Pls, add the issue link to be autoclosed once merged.

2021-07-22 07:50 UTC, pjgg commented
> Pls, add the issue link to be autoclosed once merged.

GH-89

2021-07-23 05:30 UTC, Sgitario requested changes
Some minor changes

2021-07-23 05:30 UTC, Sgitario commented on BEEFY_TS_MIGRATION_STATUS.md
> +| 023-quarkus-kamelet | kamelet |
Put this line after 021 for better readibility.

2021-07-23 05:30 UTC, Sgitario commented on kamelet/src/test/java/io/quarkus/ts/kamelet/KameletIT.java
> +    static RestService app = new RestService();
For these scenarios, you don't need to create the app. So, you can remove this declaration.
For rest assured, everything is configured for you using RestAssured.given()

2021-07-23 05:30 UTC, Sgitario commented on pom.xml
> +                <version>${quarkus.camel.version}</version>
We should add the bom dependency instead of individual dependencies: https://mvnrepository.com/artifact/org.apache.camel.quarkus/camel-quarkus-bom

2021-07-26 10:09 UTC, Sgitario approved these changes

2021-07-26 10:10 UTC, Sgitario commented
run tests

2021-07-26 13:43 UTC, Sgitario commented
The JVM failures are unrelated to this PR, so this PR is ready to be merged. Can you rebase this PR to proceed?

2021-07-26 14:11 UTC, merged