Remove PostgreSQL image workaround
quarkus-qe/quarkus-test-suite pull request #1022
Opened 2023-01-30 11:47 UTC by jsmrcka

### Summary

Removes workaround for a failure reported in
https://github.com/quarkus-qe/quarkus-test-framework/issues/641 and observed in https://github.com/quarkus-qe/quarkus-test-suite/pull/971.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-01-30 13:10 UTC, fedinskiy requested changes

2023-01-30 13:10 UTC, fedinskiy commented on sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/XAPostgresIT.java
> +    @Container(image = "${postgresql.latest.image}", port = POSTGRESQL_PORT, expectedLog = "listening on IPv4 address")
CI says `XAPostgresIT » NotFound Status 404: {"message":"No such image: postgres:15"}`

2023-02-15 13:00 UTC, rsvoboda commented
@jsmrcka pls rebase and check the failures

2023-02-27 19:15 UTC, pjgg commented
I think that this error `"message":"No such image: postgres:15"` is still happening, but currently is hidden by Hibernate 6.2 integration issues

```
ERROR: relation "hibernate_sequence" does not exist
```

2023-03-01 09:54 UTC, pjgg commented
@jsmrcka could you rebase this branch with the latest changes?

2023-03-01 16:54 UTC, pjgg commented
The error is on test framework on this class `DockerUtils#removeImageById`

Basically is a run condition as far as I see, between these two scenarios `PostgresqlDatabaseIT` , `XAPostgresIT` and the global property `ts.database.container.delete.image.on.stop=true`

As a workaround, I am going to avoid deleting portgresql image on this module.

There is already an open issue on Quarkus test framework talking about this error

https://github.com/quarkus-qe/quarkus-test-framework/issues/641

2023-03-02 09:27 UTC, pjgg approved these changes
LGTM

2023-03-02 09:31 UTC, fedinskiy approved these changes

2023-03-02 10:32 UTC, pjgg commented on sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/PostgresqlDatabaseIT.java
> +    static PostgresqlService postgresql = new PostgresqlService()
That is a good point!

So, I have added the following config

```
ts.postgresql.log.enable=true
ts.postgresql.openshift.use-internal-service-as-url=true
```

2023-03-02 11:03 UTC, jsmrcka commented on sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/PostgresqlDatabaseIT.java
> +    static PostgresqlService postgresql = new PostgresqlService()
Thank you.

2023-03-02 14:22 UTC, merged