Cover OpenAPI together with Spring Data
quarkus-qe/quarkus-test-suite pull request #1040
Opened 2023-02-06 13:25 UTC by fedinskiy

### Summary

Required for https://issues.redhat.com/browse/QUARKUS-2787
Please select the relevant options.

This is backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/1038 which is made separately due to differences between 2.13 and main

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-02-07 08:13 UTC, fedinskiy commented
The experiment considered a failure

2023-02-07 11:32 UTC, fedinskiy commented
run tests

2023-02-08 09:23 UTC, fedinskiy commented
run tests

2023-02-08 09:35 UTC, fedinskiy commented
run tests

2023-02-08 10:45 UTC, fedinskiy commented
OCP CI doesn't run on this PR for some reason, man manual tests (`mvn clean verify -Dnative -Dall-modules -pl spring/spring-data`and `mvn clean verify -Dnative -Dall-modules -pl spring/spring-data -Dnative`) showed no errors.

2023-02-08 11:30 UTC, jsmrcka requested changes

2023-02-08 11:30 UTC, jsmrcka commented on spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
> +
I'm missing some asserts about secured endpoints' security schemas:
```java
        assertEquals("admin", json.getString("paths.'/secured/deny-all/{id}'.get.security[0].SecurityScheme[0]"));
        assertEquals("admin", json.getString("paths.'/secured/roles-allowed'.get.security[0].SecurityScheme[0]"));
        assertEquals("admin", json.getString("paths.'/secured/roles-allowed/{id}'.get.security[0].SecurityScheme[0]"));

        // TODO: https://github.com/quarkusio/quarkus/issues/30997
        // assertEquals("user", json.getString("paths.'/secured/roles-allowed/{id}'.delete.security[0].SecurityScheme[0]"));
```
The last one (commented due to a bug in `smallrye-openapi`) requires an additional endpoint in https://github.com/quarkus-qe/quarkus-test-suite/blob/main/spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/RolesAllowedRepository.java:
```java
    @Override
    @RolesAllowed("user")
    void deleteById(Long aLong);
```

2023-02-08 17:25 UTC, jsmrcka commented
OCP runs:
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk11-openshift-ts-jvm/4/ - GREEN
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ts-native/4/ - GREEN

I am not yet sure about the Windows CI failure:
```
Error:  Failed to execute goal net.revelc.code:impsort-maven-plugin:1.7.0:sort (default) on project spring-data: Execution default of goal net.revelc.code:impsort-maven-plugin:1.7.0:sort failed: A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.7.0:sort: org/codehaus/plexus/util/DirectoryScanner
```
Particularly, why it started to happen all of the sudden.

2023-02-08 17:25 UTC, jsmrcka approved these changes

2023-02-08 17:38 UTC, fedinskiy commented
`mvn -B -fae -s .github/mvn-settings.xml -Dall-modules clean verify -pl spring/spring-data/ -am` worked during manual run on Windows machine (image `__QUARKUSQE-SNAPHOT-win2019-x86_64-DEPLOY`), so I consider this to be a bug on GitHub side.

2023-02-08 17:38 UTC, merged