Cover OpenAPI together with Spring Data
quarkus-qe/quarkus-test-suite pull request #1041
Opened 2023-02-06 13:30 UTC by fedinskiy

### Summary

Required for https://issues.redhat.com/browse/QUARKUS-2787
Replaces https://github.com/quarkus-qe/quarkus-test-suite/pull/1038
Backport to 2.13: https://github.com/quarkus-qe/quarkus-test-suite/pull/1040

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-02-06 14:30 UTC, fedinskiy commented
run tests

2023-02-07 10:33 UTC, jsmrcka commented
OCP runs look weird, `Scenario: ignore` was used, which is wrong. A possible bug in the dispatcher pipeline? @pjgg 
https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/main_rhel8_jdk11_openshift_ts_jvm_githubci_dispatcher/110/console
https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/main_rhel8_jdk17_openshift_ts_native_githubci_dispatcher/79/console

2023-02-08 08:51 UTC, rsvoboda commented
@mjurc ... jenkins didn't run any module, pls check the logic when working on the pipeline for this testing

2023-02-08 10:55 UTC, jsmrcka commented
Manually triggered OCP runs, using Quarkus 2.16.1.Final:
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk11-openshift-ts-jvm/1/ - GREEN
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ts-native/1/ - GREEN

(Both point to the source branch and can be rebuilt, if necessary.)

2023-02-08 11:26 UTC, jsmrcka requested changes

2023-02-08 11:26 UTC, jsmrcka commented on spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
> +
I'm missing some asserts about secured endpoints' security schemas:
```java
        assertEquals("admin", json.getString("paths.'/secured/deny-all/{id}'.get.security[0].SecurityScheme[0]"));
        assertEquals("admin", json.getString("paths.'/secured/roles-allowed'.get.security[0].SecurityScheme[0]"));
        assertEquals("admin", json.getString("paths.'/secured/roles-allowed/{id}'.get.security[0].SecurityScheme[0]"));

        // TODO: https://github.com/quarkusio/quarkus/issues/30997
        // assertEquals("user", json.getString("paths.'/secured/roles-allowed/{id}'.delete.security[0].SecurityScheme[0]"));
```
The last one (commented due to a bug in `smallrye-openapi`) requires an additional endpoint in https://github.com/quarkus-qe/quarkus-test-suite/blob/main/spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/RolesAllowedRepository.java:
```java
    @Override
    @RolesAllowed("user")
    void deleteById(Long aLong);
```

2023-02-08 17:06 UTC, jsmrcka approved these changes

2023-02-08 17:07 UTC, jsmrcka commented
Another round of OCP runs with 2.16.1.Final:
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk11-openshift-ts-jvm/3/ - GREEN
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ts-native/3/ - GREEN

2023-02-08 17:28 UTC, jsmrcka commented
CI on `main` is broken, so i did 2 local runs :
```
mvn clean verify -Dquarkus.platform.version=2.16.1.Final
mvn clean verify -Dquarkus.platform.version=2.16.1.Final -Dnative
```
Both passed.

2023-02-08 17:29 UTC, merged