[2.13] jbang + HQL queries backports
quarkus-qe/quarkus-test-suite pull request #1061
Opened 2023-02-16 09:01 UTC by pjgg

### Summary

[Add coverage for new lines in HQL queries](https://github.com/quarkus-qe/quarkus-test-suite/pull/1056) fedinskiy
[Make jbang use the same repository as maven](https://github.com/quarkus-qe/quarkus-test-suite/pull/1058) fedinskiy

Please select the relevant options.
- [X] Backport

2023-02-16 13:30 UTC, fedinskiy commented
a) There is a CI failure, I suppose we also need to backport a fix for Windows CI
b) I suggest to wait for https://github.com/quarkus-qe/quarkus-test-suite/pull/1064 to be merged and backport it as well

2023-02-17 08:06 UTC, fedinskiy requested changes
See above

2023-02-28 17:15 UTC, pjgg commented
depends on: https://github.com/quarkus-qe/quarkus-test-suite/pull/1083

2023-02-28 17:29 UTC, fedinskiy requested changes

2023-02-28 17:29 UTC, fedinskiy commented on sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java
> +        System.out.println(author.body().asString());
Do we need this output?

2023-03-01 13:02 UTC, merged