Move http-static from beefy-scenarios
quarkus-qe/quarkus-test-suite pull request #111
Opened 2021-07-22 11:00 UTC by fedinskiy

As per https://github.com/quarkus-qe/quarkus-test-suite/issues/91

2021-07-23 05:25 UTC, Sgitario commented
@fedinskiy is this PR ready to be reviewed? If not, pls change it to draft until it is. If so, pls assign anybody as a reviewer.

2021-07-26 08:04 UTC, Sgitario requested changes
Please, link the related issue to this PR and squash all the commits in one.

2021-07-26 08:04 UTC, Sgitario commented on http/http-static/pom.xml
> +    <name>Quarkus QE TS: static http content</name>
Same comment as in https://github.com/quarkus-qe/quarkus-test-suite/pull/100#discussion_r675316157

2021-07-26 08:04 UTC, Sgitario commented on http/http-static/src/test/java/io/quarkus/ts/http/LargeStaticResourceIT.java
> +@QuarkusTest
This test is not using the test framework:
1.- Change it to `@QuarkusScenario`
2.- This annotation `@TestHTTPResource("big-file")` is not working in the test framework (you can file an issue to support it). Instead, use directly given().post("/big-file"),...

2021-07-27 10:52 UTC, fedinskiy commented
@Sgitario issue linked, commits squashed, all requested changes was implemented

2021-07-27 11:28 UTC, Sgitario approved these changes
lgtm

2021-07-27 11:37 UTC, Sgitario commented
The failure is unrelated to this PR. Merging.

2021-07-27 11:37 UTC, merged