Migrate Beefy 101-javaee-like-getting-started
quarkus-qe/quarkus-test-suite pull request #121
Opened 2021-07-26 11:52 UTC by pjgg

javaee-like-getting-started migration

Migrate101-javaee-like-getting-started from Beefy-ts to quarkus-test-suite

FIX #90

2021-07-26 12:03 UTC, Sgitario requested changes
Just a minor thing in the README.md.
I don't see any scenarios for OpenShift, don't you see any value in adding some? (just asking)

2021-07-26 12:03 UTC, Sgitario commented on README.md
> +# scenario-101-getting-started
```suggestion
### `javaee-like-getting-started`
```

2021-07-26 14:56 UTC, pjgg commented on README.md
> +# scenario-101-getting-started
I don't see it either

2021-07-27 05:07 UTC, Sgitario requested changes

2021-07-27 05:07 UTC, Sgitario commented on BEEFY_TS_MIGRATION_STATUS.md
> +| 302-quarkus-vertx-jwt | security/vertx-jwt|
This line is duplicated

2021-07-29 04:58 UTC, Sgitario approved these changes

2021-07-29 05:01 UTC, merged