Many Extensions and Many Resources module
quarkus-qe/quarkus-test-suite pull request #129
Opened 2021-07-28 07:07 UTC by rsvoboda

Many Extensions and Many Resources, module is using 47 Quarkus extension and 60 REST endpoints.
The intention is to ensure such kind of big application behaves well in various target environments. 

Went a bit beyond just back-porting 003-quarkus-many-extensions, enhanced the case a bit by generating REST resources and services.

Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/76

2021-07-28 08:01 UTC, Sgitario reviewed
Just minor comments about mix of coverage between `http-minimum` and this new module.

2021-07-28 10:22 UTC, rsvoboda commented on BEEFY_TS_MIGRATION_STATUS.md
> +| 003-quarkus-many-extensions | super-size/many-extensions |
I see some future cases. Our customers do really interesting things, size of the apps is one of them.

I was also thinking that 201-large-static-content would be more appropriate fit here. I know it was planned for http module, but it's really Super Size Me scenario.

2021-07-28 10:23 UTC, rsvoboda commented on super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/DevModeHttpMinimumIT.java
> +public class DevModeHttpMinimumIT {
Good catch / will do. I used http minimum as the starting point here.

2021-07-28 10:56 UTC, rsvoboda commented on super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/DevModeHttpMinimumIT.java
> +public class DevModeHttpMinimumIT {
I have copied the tests, wanted to reuse them somehow, but `app.given()` is not defined in `BaseService` but in `RestService` and `DevModeQuarkusService`

2021-07-28 11:02 UTC, rsvoboda commented on super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/DevModeHttpMinimumIT.java
> +public class DevModeHttpMinimumIT {
I think `.given()` should be defined in BaseService, I can see cases when one wants to ensure the same test coverage on both modes. What are your thoughts @Sgitario ?

2021-07-28 11:27 UTC, Sgitario commented on super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/DevModeHttpMinimumIT.java
> +public class DevModeHttpMinimumIT {
Let's fix this for all: https://github.com/quarkus-qe/quarkus-test-framework/pull/160
Now, DevMode service will inherit from RestService (that contains the `.given()` method. 
So, you could have a base test class with your test cases and an abstract method to get the RestService app. 
A way to workaround this and have comment test cases now, it's to have an abstract method to get the `RequestSpecification given()`. This is what I did in https://github.com/quarkus-qe/quarkus-test-suite/pull/127/files#diff-a35f14131768db79aacc738139f5365b655de34efe8ef5a439a280de8b988985R19.

2021-07-28 11:28 UTC, Sgitario approved these changes

2021-07-28 12:13 UTC, Sgitario requested changes
native CI is failing

2021-07-28 12:39 UTC, rsvoboda commented
New module requires xmx set to 5g, set as property for that module, testsuite wide default is 4g

2021-07-28 13:38 UTC, rsvoboda commented on super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/DevModeHttpMinimumIT.java
> +public class DevModeHttpMinimumIT {
Cool, I can do that once new version of framework is out. Any plans / ETAs ?

2021-07-28 13:39 UTC, Sgitario commented
run tests

2021-07-29 06:22 UTC, rsvoboda commented
Failures in https://main-jenkins-csb-quarkusqe.apps.ocp4.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-new-ts-jvm/48/ look like OpenShif env related and Jenkins job related (Non-resolvable parent POM for io.quarkus.ts.qe:many-extensions:1.0.0-SNAPSHOT: io.quarkus.ts.qe:parent:pom:1.0.0-SNAPSHOT was not found)

2021-07-29 06:46 UTC, Sgitario commented
The OCP instances are again with network issues. 
I've also fixed a possible issue: https://github.com/quarkus-qe/quarkus-test-framework/commit/8e1175f1e544b188d166384ab0313d734cf98d7a which will be solved in the 0.0.4 release.
Pls, rebase your PR and I'm fine to merge this.

2021-07-29 06:46 UTC, Sgitario approved these changes

2021-08-03 07:45 UTC, rsvoboda commented
JVM run failure is not related to this PR.

Failure in  `Security: Keycloak + OIDC Client + Extended`

```
2021-08-03T07:03:34.6943556Z [ERROR] Failures: 
2021-08-03T07:03:34.6945720Z [ERROR]   OpenApiIT.testJsonOpenApiPathAccessResource:46->assertContent:76 
2021-08-03T07:03:34.6947304Z Expected: is "{\"title\":\"Generated API\",\"version\":\"1.0\"}"
2021-08-03T07:03:34.6949212Z      but: was "{\"title\":\"security-keycloak-oidc-client-extended API\",\"version\":\"1.0.0-SNAPSHOT\"}"
2021-08-03T07:03:34.6951504Z [ERROR]   OpenApiIT.testYamlOpenApiPathAccessResource:53->assertContent:76 
2021-08-03T07:03:34.6953161Z Expected: is "{\"title\":\"Generated API\",\"version\":\"1.0\"}"
2021-08-03T07:03:34.6954737Z      but: was "{\"title\":\"security-keycloak-oidc-client-extended API\",\"version\":\"1.0.0-SNAPSHOT\"}"
```

2021-08-03 07:46 UTC, rsvoboda commented
@Sgitario I think this can be merged now.

2021-08-03 15:34 UTC, merged