[DO NOT MERGE] Enable tests after fixing quarkus-qe/quarkus-test-framework#584.
quarkus-qe/quarkus-test-suite pull request #1328
Opened 2023-07-26 10:11 UTC by jedla97

### Summary

Hi, this PR remove the disabled annotation on tests affected by by quarkus-qe/quarkus-test-framework#584.
It can be merged after the quarkus-qe/quarkus-test-framework#842 is merged and new version of framework is released and updated.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-07-29 10:20 UTC, michalvavrik requested changes
@jedla97 thank you for changes. 

PR description says it enables tests, but it does not (please see CI). Tests are disabled on Windows as TestContainers don't support Windows containers and we don't have compatible docker agent ready.

Only `ReactiveRestClientProxyIT` actually needs Docker, please drop Maven profile and disable this one test on Windows so that we actually can test your changes when FW is released and bumped. Thank you

2023-08-05 17:16 UTC, michalvavrik commented
@jedla97 please rebase your PR onto main as TS is now using 1.3.0.Beta23.

2023-08-07 08:20 UTC, jedla97 commented
@michalvavrik PR rebased and test seem ok. The enabled test are running on windows now.

2023-08-07 09:36 UTC, michalvavrik approved these changes
LGTM

2023-08-07 09:36 UTC, merged