Rename outdated properties
quarkus-qe/quarkus-test-suite pull request #1330
Opened 2023-07-26 11:45 UTC by fedinskiy

### Summary

Rename properties, which were removed[1] two years ago

[1] https://github.com/quarkus-qe/quarkus-test-framework/pull/309

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-07-26 11:45 UTC, fedinskiy commented
run tests

2023-07-26 11:53 UTC, michalvavrik reviewed
perfect :-D, can you remove them from README as well, please?

2023-07-26 11:55 UTC, rsvoboda commented
And check the Jenkins jobs definitions too.

2023-07-26 12:13 UTC, fedinskiy commented
README changed.

`quarkus-qe/jenkins-jobs` doesn't use these options

2023-07-26 13:48 UTC, michalvavrik commented
run tests

2023-07-26 20:07 UTC, michalvavrik commented
@fedinskiy could you please check 120 failures in native OCP run?

2023-07-26 20:11 UTC, michalvavrik commented on pom.xml
> +                                <quarkus.s2i.base-jvm-image>${quarkus.s2i.base-jvm-image}</quarkus.s2i.base-jvm-image>
For OpenShift, Quarkus docs say it uses OpenJDK 17 for 17+ and 11 for 11 builds https://quarkus.io/guides/all-config#quarkus-container-image-openshift_quarkus.s2i.base-jvm-image. Are you sure we really want to use 11 in all cases? IIRC until now when not specified, we were using default which is OpenJDK 17 from `io.quarkus.test.services.quarkus.model.QuarkusProperties#QUARKUS_JVM_S2I`.

2023-07-27 09:26 UTC, fedinskiy commented
@michalvavrik I can reproduce the same failure ("xargs is not available") on 4-13 for `3.2.0.Final`,`3.2.1.Final` and `3.2.2.Final` even on `main`. It seems to me, that something is very wrong with our basic image. I will rerun weekly check to verify it.

2023-07-28 15:16 UTC, fedinskiy commented
Hmm, it looks like the culprit is this image, which is being regularly updated: https://quay.io/repository/quarkus/ubi-quarkus-graalvmce-s2i?tab=history

2023-07-29 10:26 UTC, michalvavrik approved these changes
I think this change is correct.

2023-07-29 10:27 UTC, michalvavrik commented
run tests

2023-07-31 12:38 UTC, fedinskiy commented
run tests

2023-07-31 19:21 UTC, michalvavrik requested changes
I tested it with / without your changes and `OpenShiftWorkshopHeroesIT` failure is direct consequence of this PR, please find a solution. My suggestion would be to use openjdk-17 as I already mentioned before. Thanks

2023-08-01 07:37 UTC, fedinskiy commented
@michalvavrik I changed the property to use the same basic JVM image we already use in the fw.

2023-08-01 07:46 UTC, fedinskiy commented
run tests

2023-08-01 08:04 UTC, michalvavrik approved these changes

2023-08-01 19:36 UTC, michalvavrik commented
I can reproduce OCP failures on main as well, therefore they are not related. JVM simply timed out.

2023-08-01 19:36 UTC, merged