Add test for SSE reactive.
quarkus-qe/quarkus-test-suite pull request #1517
Opened 2023-11-13 16:05 UTC by jedla97

### Summary

Adding the test based on scenario from https://github.com/quarkusio/quarkus/issues/35966. When developing it there are some issues so for now it's disabled (https://github.com/quarkusio/quarkus/issues/37033 and https://github.com/quarkusio/quarkus/issues/36986). 

Test should run on ocp as well but as it it disable I don't see much point to run it now.

Maybe it would be nice to add this scenario (with empty request) to http-advanced (non-reactive)? There is recent test for SSE but with this there will need be some small adjustment to it. WDYT?

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2023-11-13 19:55 UTC, michalvavrik commented
> Maybe it would be nice to add this scenario (with empty request) to http-advanced (non-reactive)? There is recent test for SSE but with this there will need be some small adjustment to it. WDYT?

My impression is that RESTEasy Classic and SSE don't go together too well: https://github.com/quarkus-qe/quarkus-test-suite/pull/1511#issuecomment-1805335024

2023-11-13 20:02 UTC, michalvavrik requested changes
You checked off `follow the best practices https://cbea.ms/git-commit/` but in https://cbea.ms/git-commit/ I can see rule number 4. _Do not end the subject line with a period_ Can you please try to provide more descriptive PR title? I know it's hard, I hardly ever do it right, but I think you can do better. Thanks

2023-11-14 11:28 UTC, michalvavrik commented
@jedla97 lgtm (+ please address note above on PR title), but let's wait to https://github.com/quarkusio/quarkus/pull/37035 and enable native test before this go in

2023-11-14 11:31 UTC, jedla97 commented on http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/SseEventUpdateResource.java
> +        eventSource.register(ev -> {
Updated. Used `CopyOnWriteArrayList`. As the string is inside of lambda it's not possible to use string outside of it (unless it's use atomic). I look inside of Quarkus test coverage and it have only kotlin test which using `Collections.synchronizedList`.

2023-11-14 11:31 UTC, jedla97 commented on http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/SseEventUpdateResource.java
> +    @Context
Fixed

2023-11-14 11:34 UTC, jedla97 commented on http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/SseEventUpdateResource.java
> +        LockSupport.parkNanos(5_000_000_000L);
Updated. Look at the waiting more and there is some time needed to consume and work with events. But 1 second should be enough.

2023-11-14 11:40 UTC, jedla97 commented on http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/SseEventUpdateResource.java
> +        eventSource.close();
I add try-with-resources. Personally tried when there is error status is not 200. It's caught in `eventSource.register` state. So believe it`s  inside logic which catch it. The eventsource operation should only throw `
IllegalArgumentException` when the some parameter is null. In this case it should not happen.

2023-11-14 11:42 UTC, jedla97 commented
@michalvavrik Title updated, Last push was just change commit typo. No problem waiting. Hope it will be quick

2023-11-15 12:21 UTC, michalvavrik commented
@jedla97 I'm starting to think upstream PR won't go in anytime soon. Please rebase so that we can get this in.

2023-11-15 14:53 UTC, jedla97 commented
run tests

2023-11-15 15:43 UTC, michalvavrik approved these changes

2023-11-15 16:24 UTC, merged