Add coverage of `quarkus-cache`
quarkus-qe/quarkus-test-suite pull request #166
Opened 2021-08-11 07:28 UTC by Sgitario

Verifies the `quarkus-cache` extension using `@CacheResult`, `@CacheInvalidate` and `@CacheKey`.
It covers different usages: 
1. from an application scoped service
2. from a request scoped service
3. from a blocking endpoint
4. from a reactive endpoint

2021-08-13 10:51 UTC, kshpak commented
I failed to run OpenShift tests
I do: `mvn clean verify -pl cache/caffeine/ -Popenshift -Dts.container.registry-url=https://quay.io/organization/quarkusqeteam`
Parameter `-Dts.container.registry-url` seems required, how it is handled in Jenkins?

2021-08-13 11:31 UTC, kshpak commented
I was able to push image into registry with another URL format:
```
 mvn clean verify -pl cache/caffeine/ -Dopenshift -Dts.container.registry-url=quay.io/quarkusqeteam
```
BUT, now the ImagePullBackOff error on OpenShift side (clearly because it don't have rights to pull it)
On `quay` side the image has private modifier.

2021-08-13 11:35 UTC, Sgitario commented
> I was able to push image into registry with another URL format:
> 
> ```
>  mvn clean verify -pl cache/caffeine/ -Dopenshift -Dts.container.registry-url=quay.io/quarkusqeteam
> ```
> 
> BUT, now the ImagePullBackOff error on OpenShift side (clearly because it don't have rights to pull it)
> On `quay` side the image has private modifier.

@kshpak my bad. I used to play with the container registry deployment strategy when developing a new scenario because it's much faster. I've already removed this, so you don't need to supply any parameters.

For next time you want to use the container registry, you need to be logged in and have permission to make public the new repository in quay.io.

2021-08-16 05:14 UTC, Sgitario commented
run tests

2021-08-16 05:42 UTC, Sgitario commented
OCP is again unestable: `oc: Unable to connect to the server: dial tcp 10.0.205.16:6443: i/o timeout`

2021-08-16 06:05 UTC, kshpak requested changes
Small changes
Question: how RequestScope vs ApplicationScope will differ? I assume calling `request-scope` service from a terminal window and from browser window should get different values, isn't it?

2021-08-16 06:16 UTC, Sgitario commented
> Small changes
> Question: how RequestScope vs ApplicationScope will differ? I assume calling `request-scope` service from a terminal window and from browser window should get different values, isn't it?

No, it should get the same value. The difference is that beans annotated with `@ApplicationScope` are created once per application where beans with `@RequestScope` once per request, hence we need to ensure that the cache works even when the bean has just been created.

2021-08-16 06:17 UTC, Sgitario commented on README.md
> +Verifies the `quarkus-cache` extension using `@CacheResult`, `@CacheInvalidate` and `@CacheKey`.
Added

2021-08-16 06:17 UTC, Sgitario commented on cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/ServiceWithCacheResourceIT.java
> +                "Value was equal which means cachekey didn't work");
Updated

2021-08-16 06:31 UTC, kshpak approved these changes

2021-08-16 06:32 UTC, merged