Split Native job to run selected modules
quarkus-qe/quarkus-test-suite pull request #183
Opened 2021-08-17 05:05 UTC by Sgitario

The idea would be to run the modules that take the most of the time in individual jobs, so the jobs do not exceed the timeout.

++ Update Mandrel image to use 21.2
++ Update reason of @DisabledOnNative for S2i deployments. Caused by: https://github.com/quarkus-qe/quarkus-test-framework/issues/206
++ Exclude DevMode tests on Native by Maven configuration
++ Refactor scheduling/quartz module to run tests on Native without build

Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/154

2021-08-17 05:34 UTC, Sgitario commented
Running Daily run test in https://github.com/Sgitario/quarkus-test-suite/runs/3347279091?check_suite_focus=true

2021-08-17 13:41 UTC, rsvoboda requested changes

2021-08-17 13:41 UTC, rsvoboda commented on .github/workflows/daily.yaml
> +        image: [ "ubi-quarkus-native-image:21.0-java11", "ubi-quarkus-mandrel:21.2-java11" ]
```suggestion
        image: [ "ubi-quarkus-native-image:21.2-java11", "ubi-quarkus-mandrel:21.2-java11" ]
```

2021-08-17 13:41 UTC, rsvoboda commented on .github/workflows/quarkus-test-framework-snapshot.yaml
> +        image: [ "ubi-quarkus-native-image:21.0-java11", "ubi-quarkus-mandrel:21.2-java11" ]
```suggestion
        image: [ "ubi-quarkus-native-image:21.2-java11", "ubi-quarkus-mandrel:21.2-java11" ]
```

2021-08-17 13:41 UTC, rsvoboda commented on external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartUsingS2iIT.java
> +@DisabledOnNative(reason = "S2i is not supported on Native yet: https://github.com/quarkus-qe/quarkus-test-framework/issues/206")
I think S2I for native needed some special Quarkus image which was supported just on community side. On product side native build using S2I wasn't supported. 

We used that community image for Native S2I in OpenShiftTS. @mjurc can you point to the details?
Ideally update https://github.com/quarkus-qe/quarkus-test-framework/issues/206

2021-08-17 14:51 UTC, Sgitario commented on .github/workflows/quarkus-test-framework-snapshot.yaml
> +        image: [ "ubi-quarkus-native-image:21.0-java11", "ubi-quarkus-mandrel:21.2-java11" ]
Updated

2021-08-17 14:51 UTC, Sgitario commented on .github/workflows/daily.yaml
> +        image: [ "ubi-quarkus-native-image:21.0-java11", "ubi-quarkus-mandrel:21.2-java11" ]
Updated

2021-08-19 09:49 UTC, Sgitario commented
@rsvoboda this is ready to be reviewed now.
The main implications are that we have moved the modules into profiles, so we can now easily select and unselect groups quite. After these changes, the daily run is finally finished ok in time.
The disadvantage is that when we select other profiles (for example, openshift or native), we need to explicitly add the property `-Dinclude.all-modules`. 
I didn't update the documentation or update the Jenkins jobs because I wanted to know what you think about the current solution.

2021-08-19 16:02 UTC, rsvoboda requested changes
`-Dinclude.all-modules` next to `-Dinclude.quarkus-cli-tests` doesn't feel right to me. I would just use `-Dall-modules`.
I think the split is needed and I don't think Maven gives us better ways how to handle combinations of profiles with default ones.

Please update the README

https://github.com/quarkus-qe/quarkus-test-framework/pull/208 was merged, `@DisabledOnNative` for S2i deployments could be removed imho.

2021-08-20 05:33 UTC, Sgitario commented
> `-Dinclude.all-modules` next to `-Dinclude.quarkus-cli-tests` doesn't feel right to me. I would just use `-Dall-modules`.
> I think the split is needed and I don't think Maven gives us better ways how to handle combinations of profiles with default ones.
> 
> Please update the README
> 
> [quarkus-qe/quarkus-test-framework#208](https://github.com/quarkus-qe/quarkus-test-framework/pull/208) was merged, `@DisabledOnNative` for S2i deployments could be removed imho.

Changed `-Dinclude.all-modules` to `-Dall-modules`.
I didn't remove the disabled on native for S2i deployments as this should be done after upgrading the test framework to 0.0.7. Moreover, we need to map the `quarkus.s2i.base-jvm-image` and `quarkus.s2i.base-native-image` properties to work properly.

Just a note, we could improve the situation by removing the rest of the profiles (openshift, native, validate-format, quarkus-cli-tests, operator-scenarios, include.serverless, redhat-registry). These profiles are only about to update some properties, so we could provide these properties directly to the Maven command instead of using a property to activate the Maven profile. This way we don't need to explicitly add the `-Dall-modules` almost all the times.

2021-08-20 06:49 UTC, rsvoboda commented
I would keep openshift, native, validate-format, quarkus-cli-tests, operator-scenarios, include.serverless, redhat-registry profiles, they are handy and sort of abstraction if we need to adjust the underlying properties

2021-08-20 06:55 UTC, rsvoboda approved these changes

2021-08-20 07:37 UTC, merged