Add coverage for Infinispan cache extension
quarkus-qe/quarkus-test-suite pull request #1914
Opened 2024-08-02 14:08 UTC by gtroitsk

### Summary
Test coverage for QQE-832
TP: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QQE-832.md 

New tests:
- Use [custom POJOs](https://quarkus.io/guides/cache-infinispan-reference#marshalling-your-pojos) as cache value, verify marshalling in Quarkus Infinispan. See `ExpensiveResponse` in cache service.
-  Test [Cache expiration](https://quarkus.io/guides/cache-infinispan-reference#expiration)  properties. `testCacheLifespan` and `testCacheMaxIdle`.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-08-02 14:14 UTC, gtroitsk commented
run tests

2024-08-02 14:51 UTC, fedinskiy commented
are there any test plans?

2024-08-02 15:02 UTC, gtroitsk commented
> are there any test plans?

No test plan, if you require it I can create. The tests except caffeine cases must cover complex Java types marshalling and cache expiration. I went through [docs](https://quarkus.io/guides/cache-infinispan-reference) and [upstream PR](https://github.com/quarkusio/quarkus/pull/39836)

2024-08-05 09:40 UTC, fedinskiy requested changes
Also, what about tracing and metrics? Does this extensions generate any?

2024-08-05 09:40 UTC, fedinskiy commented on cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/BaseServiceWithCache.java
> +    private static int counter = 0;
It seems, that this value may potentially be changed from the several threads. Please, change this variable to Atomic or another race-protected alternative

2024-08-06 08:25 UTC, rsvoboda commented
TP needs to be done for new features landing in product support

2024-08-07 11:28 UTC, gtroitsk commented
run tests

2024-08-08 06:58 UTC, fedinskiy approved these changes
But please double-check, that failures in CI are unrelated

2024-08-08 08:36 UTC, gtroitsk commented
Failures are unrelated for this PR, I work on them in the part of other task

2024-08-08 08:43 UTC, fedinskiy commented
@gtroitsk could you link the task for a reference?

2024-08-08 09:34 UTC, gtroitsk commented
> @gtroitsk could you link the task for a reference?

QQE-866

2024-08-08 09:40 UTC, merged