[3.8] Re-enable tests on IBM platforms due to removal of zookeeper
quarkus-qe/quarkus-test-suite pull request #2030
Opened 2024-09-19 15:38 UTC by dale-fu

### Summary

Due to https://github.com/quarkus-qe/quarkus-test-suite/pull/1854, we can re-enable the tests that were using the zookeeper image on IBM platforms. The previously skipped tests passing on latest 3.8 release.

Example test runs:
- https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk17-new/40/
- https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk21-new/46/

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-09-19 15:39 UTC, dale-fu commented
Will need to backport into main and most likely 3.15 branch afterwards.

2024-09-20 07:17 UTC, michalvavrik requested changes
@dale-fu please address formatting issues

2024-09-20 14:51 UTC, michalvavrik commented
let's try again @dale-fu

2024-09-20 14:59 UTC, dale-fu commented
I'm so confused, all I did was remove DisabledIfSystemProperty(), I don't even think I touched the imports. Looking at the log, it seems like the imports are already alphabetical on OperatorOpenShiftAmqStreamsKafkaStreamIT.java.

2024-09-20 15:02 UTC, michalvavrik commented
> I'm so confused, all I did was remove DisabledIfSystemProperty(), I don't even think I touched the imports. Looking at the log, it seems like the imports are already alphabetical on OperatorOpenShiftAmqStreamsKafkaStreamIT.java.

You have removed `DisabledIfSystemPropert`, unused imports are not allowed. Please drop it.

2024-09-20 16:09 UTC, michalvavrik approved these changes

2024-09-20 16:30 UTC, merged