Backport picoccli-native fix to 3.15
quarkus-qe/quarkus-test-suite pull request #2061
Opened 2024-10-03 15:26 UTC by jcarranzan

### Summary

Backport picoccli-native fix to 3.15

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-10-03 22:44 UTC, michalvavrik requested changes
1. CI is failing because you didn't bump Quarkus QE framework to the 1.5.4 https://github.com/quarkus-qe/quarkus-test-suite/blob/10950492c161e27574f987fd02f10bf10f27cd9f/pom.xml#L22
2. Not sure why you backport one PR when there are others with backport label

2024-10-04 07:55 UTC, fedinskiy requested changes
This commit do not reference the original one, see quarkus-qe/signpost/-/blob/main/pull-requests.md?ref_type=heads#backports-into-branches  in our gitlab

2024-10-04 08:23 UTC, michalvavrik commented
> Unknown format for flaky report filename: flaky-run-report.json

this happens because I didn't backport naming conventions to the 3.15, probably should do it

2024-10-04 14:38 UTC, fedinskiy commented
This pr is empty

2024-10-04 16:00 UTC, closed without merging