Disable tests that have no IBM ppc64le or s390x supporting images
quarkus-qe/quarkus-test-suite pull request #2116
Opened 2024-10-22 19:38 UTC by redmark-redhat

### Summary

Disable tests that have no IBM ppc64le or s390x supporting images. Also, reference images, in the POM file, that do support ppc64le or s390x.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-10-23 08:55 UTC, fedinskiy approved these changes

2024-10-23 09:35 UTC, mjurc approved these changes

2024-10-23 11:16 UTC, fedinskiy commented
@redmark-redhat there are some conflicts

2024-10-23 11:57 UTC, redmark-redhat commented
@fedinskiy conflicts are resolved.

2024-10-23 22:38 UTC, michalvavrik commented
> @fedinskiy conflicts are resolved.

no, they are not

2024-10-24 07:19 UTC, michalvavrik requested changes
@mjurc @fedinskiy please don't merged this PR until questions are answered here https://github.com/quarkus-qe/quarkus-test-suite/pull/2123#pullrequestreview-2391526992

2024-10-25 12:25 UTC, michalvavrik commented
> [redmark-redhat](https://github.com/redmark-redhat) requested a review from [michalvavrik](https://github.com/michalvavrik) [30 minutes ago](https://github.com/quarkus-qe/quarkus-test-suite/pull/2116#event-14871880914)

@redmark-redhat not sure why are you requesting my review? You are disabling classes you don't need to, we discussed it in several channels by now (Slack, other PRs), you don't run baremetal tests, so why are you disabling them?

2024-10-25 12:57 UTC, redmark-redhat commented
@michalvavrik I guess I'm unclear which are baremetal tests and which are openshift tests.  I see some tests are `@OpenShiftScenario` which I believe is openshift. How are baremetal ones tagged?

To disable ones like MSSQL I followed the `aarch64` way.  Any tests that had `@DisabledIfSystemProperty(named = "ts.arm.missing.services.excludes", matches = "true", disabledReason = "https://github.com/quarkus-qe/quarkus-test-suite/issues/2017")` I removed it for ppc64le and s390x.

2024-10-25 13:08 UTC, michalvavrik commented
@redmark-redhat you could see that in Maven POM file, because there are exclusion patterns, but I am happy to translate it for you. Here you go:

- it is an OpenShift test if test class name starts with `OpenShift`
- it is not an OpenShift test if test class name starts with `OpenShift`

2024-10-25 13:10 UTC, fedinskiy commented
@redmark-redhat any test which is not tagged with Openshift (and is not called  OpenShift${something}IT) is a baremetal one.
Baremetal tests are run on the same machine where you start the execution. Openshift tests are run on the cluster, to which you're currently connected (via `oc` cli). When you run openshift tests, the baremetal ones are disabled automatically (see profiles in pom.xml).
As far as we know, you do not start you execution on IBM machines, so it makes no sense for you to run baremetal tests and thus no need to disable any of them via annotations. 
Please disable Openshift tests you have problems with, remove any changes to baremetal tests and check you Jenkins config, so you wouldn't run any baremetal tests accidentally.

2024-10-25 13:12 UTC, redmark-redhat commented
Thanks,  I'll backout the baremetal changes ASAP.

2024-10-25 13:28 UTC, michalvavrik approved these changes
LGTM

2024-10-25 13:30 UTC, michalvavrik commented
@redmark-redhat 5 commits is bit excessive for such a PR, could you please squash it?

2024-10-25 13:31 UTC, redmark-redhat commented
Sure, I have a meeting now but will do it ASAP.

2024-10-25 14:06 UTC, fedinskiy commented
And please resolve conflicts, since they are stopping the merge, @redmark-redhat

2024-10-25 14:08 UTC, closed without merging

2024-10-25 14:09 UTC, redmark-redhat commented
I'll close the PR and rework fresh and clean on Monday.