Disable tests that have no IBM ppc64le or s390x supporting images.
quarkus-qe/quarkus-test-suite pull request #2123
Opened 2024-10-23 14:56 UTC by redmark-redhat

Disable tests that have no IBM ppc64le or s390x supporting images.  Also, fix some tests to use images that do support ppc64le or s390x.

Also, see PR https://github.com/quarkus-qe/quarkus-test-suite/pull/2116

### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] Dependency update
- [ x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x ] Methods and classes used in PR scenarios are meaningful
- [ x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2024-10-24 07:16 UTC, michalvavrik requested changes
I think this PR goes in a wrong direction. You do not test baremetal tests, so you do not need to run them or disable them. I have told your colleagues that these tests run because of the `'-Dtest=!OpenShiftTodoDemoIT'` in your command. If you really want to test baremetal tests, than please let me know. Thank you

2024-10-24 11:37 UTC, redmark-redhat commented
@michalvavrik Correct we should not test baremetal.  

If you examine the test run here (https://main-jenkins-csb-pz.apps.ocp-c1.prod.psi.redhat.com/job/manual/job/rhr/job/Cloud-Native-Runtimes/job/Quarkus/job/rhbq-3.15.x-jdk-17-21/SCENARIO=databases-modules,label=OpenstackNode-valen2/62/) we don't have '-Dtest=!OpenShiftTodoDemoIT' set and we still see Oracle and MSSQL test(s) that would be executed. Here I have the disable logic and it skips them.

Is there a better way to skip/exclude these test(s)?



![image](https://github.com/user-attachments/assets/0d45e6c1-7595-4211-8257-ed34c384ee32)
![image](https://github.com/user-attachments/assets/2e83b2d7-5071-40c0-92b7-586a80aac056)
![image](https://github.com/user-attachments/assets/2eefda97-9138-4aa1-bc3e-bd668c66957c)
![image](https://github.com/user-attachments/assets/f00f7212-712d-4c99-ad3e-b7b6ccb648c0)

2024-10-24 12:06 UTC, michalvavrik commented
I'll put it this way @redmark-redhat , only reason why I block this is that these exclusions **SHOULD** work and the fact that they don't shows other problem in a Maven command, not in the TS. Why should you care? Basically you are trying to fix failures, but you still running baremetal tests that are not failing or you can if we add new ones that doesn't require unsupported images. Therefore I think this is plain Maven problem and you need to debug it. I can help with debugging, though I think you would manage yourself. Write to the Slack IBM RHBQ channel and we can talk about that. Thanks

2024-10-24 12:21 UTC, redmark-redhat commented
@michalvavrik Yes, the exclusions are working. I was pointing out that we need the `DisabledIfSystemProperty` to block the Oracle and MSSQL tests in Openshift testing mode. I've removed the `-Dtest=!OpenShiftTodoDemoIT` so it is no longer in play.

2024-10-24 12:32 UTC, michalvavrik commented
> @michalvavrik Yes, the exclusions are working. I was pointing out that we need the `DisabledIfSystemProperty` to block the Oracle and MSSQL tests in Openshift testing mode. I've removed the `-Dtest=!OpenShiftTodoDemoIT` so it is no longer in play.

I am getting lost, you provided link, I debugged it and exclusions didn't work for unit tests, so I fixed it here https://github.com/quarkus-qe/quarkus-test-suite/pull/2131. If you need to disable OpenShift tests because there is no image you could use on your system platform, please do it. But it requires adjustments in this PR.

2024-10-24 12:34 UTC, michalvavrik commented
I agree you are disabling tests in a right way if that is what you mean. My comments were regarding only disabling that are unnecessary, but we already concluded that.

2024-10-25 13:28 UTC, michalvavrik approved these changes
LGTM

2024-10-25 13:30 UTC, michalvavrik commented
@redmark-redhat if you can squash commits, that would be great

2024-10-25 13:31 UTC, redmark-redhat commented
Sure, I have a meeting now but will do it ASAP.

2024-10-25 14:09 UTC, closed without merging

2024-10-25 14:09 UTC, redmark-redhat commented
I'll close the PR and rework fresh and clean on Monday.