Move on to new Quarkus apicurio registry library
quarkus-qe/quarkus-test-suite pull request #216
Opened 2021-09-02 11:17 UTC by pjgg

depends on: https://github.com/quarkus-qe/quarkus-test-framework/pull/230

New Quarkus Apicurio registry library was released in order to produce/consumer Kafka AVRO messages. 
If you are using Kafka Strimzi the only dependency that is required are:

`io.quarkus:quarkus-avro` // Quarkus extension for generating Java code from Avro schemas
`io.quarkus:quarkus-apicurio-registry-avro`// in order to integrate Apirurio AVRO registry into Quarkus app

Doc Ref: https://quarkus.io/guides/kafka-schema-registry-avro

2021-09-07 10:52 UTC, rsvoboda commented
@pjgg conflic on pom.xml / @Sgitario when do you plan to release new version of the framework ?

2021-09-07 10:54 UTC, Sgitario commented
> @pjgg conflic on pom.xml / @Sgitario when do you plan to release new version of the framework ?

Probably tomorrow.

2021-09-08 15:00 UTC, Sgitario commented
@pjgg please update this PR

2021-09-10 10:29 UTC, Sgitario commented
run tests

2021-09-10 10:50 UTC, Sgitario requested changes
The test OpenShiftStrimziKafkaAvroIT is failing in JVM.
I tried locally and didn't help. 

Update: adding  .withProperties("strimzi-application.properties") and , registryPath = "/apis/registry/v2", it works.

2021-09-10 11:37 UTC, Sgitario commented
run tests

2021-09-10 12:36 UTC, Sgitario approved these changes

2021-09-10 12:36 UTC, merged