Upgrade docker version images
quarkus-qe/quarkus-test-suite pull request #296
Opened 2021-09-20 11:12 UTC by pjgg

The following docker images version has been updated: 
postgresql ->  13.4.0
mariadb -> 10.6.4
Keycloak -> 15.0.2

Strimzi/Apicurio is updated in Quarkus-test-framework: https://github.com/quarkus-qe/quarkus-test-framework/pull/272

2021-09-20 11:14 UTC, Sgitario commented on pom.xml
> +                                <mariadb.1064.image>quay.io/quarkusqeteam/mariadb:10.6.4</mariadb.1064.image>
I would prefer simply `mariadb.10.6.4`.

2021-09-20 20:36 UTC, mjurc approved these changes
LGTM

2021-09-21 06:15 UTC, Sgitario requested changes
Please, update the `sql-db/sql-app` section in the README too.
Pending to clarification that we're losing the redhat images coverage.

2021-09-21 10:02 UTC, Sgitario approved these changes

2021-09-21 10:22 UTC, mjurc requested changes
Actually, thinking on it now - did we not agree to keep coverage for both latest upstream and RH scl images?

2021-09-21 10:33 UTC, pjgg commented
> Actually, thinking on it now - did we not agree to keep coverage for both latest upstream and RH scl images?

The only RH image that I have changed is MariaDB, but Is in bare metal. I thought that we will use RH images only in Openshift-ts but we are not going to use the latest one yet because some of them require authentication, and we have to double-check if the TestFW supports it.

2021-09-21 12:52 UTC, Sgitario commented
The mariadb image in quay.io was not public. I've changed it and retriggered the CI.

2021-09-22 10:09 UTC, Sgitario commented
run tests

2021-09-22 21:31 UTC, mjurc commented
run tests

2021-09-23 05:40 UTC, Sgitario requested changes
The tests using MariaDB:10.6.4 are not working in OpenShift:

```
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] mariadbd: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] mariadbd: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] Plugin 'Aria' init function returned error.&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: The error means mariadbd does not have the access rights to the directory.&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: The error means mariadbd does not have the access rights to the directory.&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: Cannot open datafile './ibdata1'&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!&amp#27;[0m
01:25:30.519 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] InnoDB: Database creation was aborted with error Cannot open a file. You may need to delete the ibdata1 file before trying to start up again.&amp#27;[0m
01:25:30.520 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] Plugin 'InnoDB' init function returned error.&amp#27;[0m
01:25:30.520 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.&amp#27;[0m
01:25:30.520 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] Failed to initialize plugins.&amp#27;[0m
01:25:30.520 INFO  &amp#27;[0;34m[database] 2021-09-23  1:25:28 0 [ERROR] Aborting&amp#27;[0m
```

This is affecting OpenShift tests using the new Maria DB: quay.io/quarkusqeteam/mariadb:10.6.4. We need to investigate why this image is incompatible with OpenShift before merging this PR.

2021-09-27 05:05 UTC, Sgitario commented
run tests

2021-09-27 05:21 UTC, Sgitario commented
run tests

2021-09-27 07:53 UTC, Sgitario commented
run tests

2021-09-27 07:56 UTC, Sgitario commented
run tests

2021-09-27 11:47 UTC, Sgitario commented
run tests

2021-09-28 04:18 UTC, Sgitario requested changes
There are still failures on OpenShift: https://main-jenkins-csb-quarkusqe.apps.ocp4.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-new-ts-jvm/114/testReport/

Some failures are related to these changes: https://main-jenkins-csb-quarkusqe.apps.ocp4.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-new-ts-jvm/114/testReport/io.quarkus.ts.spring.web.boostrap/OpenShiftBookResourceIT/io_quarkus_ts_spring_web_boostrap_OpenShiftBookResourceIT/

2021-09-28 09:03 UTC, pjgg commented
run tests

2021-09-28 13:11 UTC, Sgitario approved these changes

2021-09-29 09:03 UTC, mjurc approved these changes

2021-09-29 09:03 UTC, merged