Fix spring-web modules
quarkus-qe/quarkus-test-suite pull request #366
Opened 2021-11-02 12:33 UTC by jsmrcka

Fixes modules broken by
https://github.com/quarkusio/quarkus/pull/21089.

2021-11-02 13:02 UTC, rsvoboda requested changes
Commit message should be improved to describe the nature of the change.

`Add RESTEasy Classic dependencies as RESTEasy Classic and quarkus-spring-web were decoupled` sounds more descriptive

2021-11-02 14:29 UTC, kshpak requested changes
quarkus-cli test needs to be adjusted as well

2021-11-02 14:34 UTC, kshpak commented
@jsmrcka just fyi beefy-ts needs to be changed as well
quarkus-cli test with quarkus-srping-web also used in quarkus-test-framework I will prepare PR for that

2021-11-03 09:43 UTC, kshpak approved these changes

2021-11-03 13:28 UTC, jsmrcka commented
run tests

2021-11-04 05:59 UTC, jsmrcka commented
run tests

2021-11-04 09:49 UTC, jsmrcka commented
run tests

2021-11-04 12:03 UTC, pjgg commented
Jenkins jobs are failing due to environmental issues not related to this PR

2021-11-04 12:03 UTC, merged