Quarkus_cli re-start application scenario
quarkus-qe/quarkus-test-suite pull request #370
Opened 2021-11-04 11:13 UTC by pjgg

2021-11-04 15:13 UTC, kshpak commented
@pjgg provide some description pls, it would be easier to grasp

2021-11-04 16:05 UTC, pjgg commented
> @pjgg provide some description pls, it would be easier to grasp

Quarkus-cli scenario failed last week due to an error in upstream that this week seems to be fixed(or at least we can't not reproduce with the same test). This PR will rollback the changes that we did last week where we created a new test to cover this scenario and do a walkaround to bypass this error in an existing scenario.

If tomorrow the daily build pass we can close the issue in upstream

2021-11-05 05:22 UTC, jsmrcka requested changes

2021-11-05 05:22 UTC, jsmrcka commented on quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
> -        startAfter(app, Duration.ofSeconds(CMD_DELAY_SEC));
There are unused constants left in this class: `CMD_DELAY_SEC` and `SMALLRYE_OPENAPI`. Plus the method `shouldAddAndRemoveExtensions` declares an `InterruptedException` which is never being thrown.

Maybe just do a revert of https://github.com/quarkus-qe/quarkus-test-suite/pull/361, that should take care of everything.

2021-11-05 05:26 UTC, jsmrcka commented
Please rename the PR/commit to make it clear it reverts the https://github.com/quarkus-qe/quarkus-test-suite/pull/361 and link it in the description.

2021-11-05 08:27 UTC, jsmrcka requested changes
See https://github.com/quarkus-qe/quarkus-test-suite/pull/370#issuecomment-961636812

2021-11-05 09:11 UTC, jsmrcka approved these changes

2021-11-05 10:51 UTC, merged