Introduce reactive counterparts of http-minimum and rest-client modules under /http
quarkus-qe/quarkus-test-suite pull request #388
Opened 2021-11-18 13:40 UTC by kshpak

2021-11-18 14:55 UTC, kshpak commented
Looking into native CI fail with rest-client-reactive

2021-11-22 07:43 UTC, jsmrcka requested changes
The two new modules are missing from the `README.md`. I think that something like this would be enough:
> Reactive equivalent of `http/http-minimum`.
> Reactive equivalent of `http/rest-client`.

Moreover, I am afraid I also forgot to add `http-advanced` to the README in https://github.com/quarkus-qe/quarkus-test-suite/pull/386. Could you please do it in this PR?
> Reactive equivalent of `http-advanced`.

As for the lack of XML serialization support in reactive rest client: is it documented somewhere? I was not able to find any explicit info on this. We should at least mention in the README, and add a link to the docs if possible.
If it is an open issue in quarkus (i.e. the support is expected to be added in foreseeable future), we should keep the XML-related code in the module, just disable the test and tag it with a link to the issue.

2021-11-22 09:11 UTC, kshpak commented
@jsmrcka README updated

2021-11-22 09:41 UTC, jsmrcka approved these changes

2021-11-22 14:21 UTC, pjgg approved these changes

2021-11-22 14:21 UTC, merged