Fix fails due to DockerHub limit
quarkus-qe/quarkus-test-suite pull request #549
Opened 2022-02-28 13:10 UTC by fedinskiy

2022-02-28 23:50 UTC, mjurc requested changes

2022-02-28 23:50 UTC, mjurc commented on pom.xml
> +                                <oracle.image>quay.io/quarkusqeteam/oracle-xe:21.3.0-slim</oracle.image>
Let's not specify micro-release here and go with just `oracle-xe:21-slim`, even if it is going to be in Quay

2022-02-28 23:50 UTC, mjurc commented on sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
>      private static final String MARIA_DB_VERSION = "5.5.49";
This is an ancient tag, last pushed into 6 years ago - we should definitely bump it to 10.8 (I guess), and drop the micro release version

2022-02-28 23:50 UTC, mjurc commented on sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlIT.java
> +    private static final String DB_VERSION = "8.0.24";
Let's drop the micro here aswell and use `8.0`

2022-04-27 19:04 UTC, rsvoboda commented
Closing as we are moving back to the dockerhub as bitnami is gone from quay

2022-04-27 19:04 UTC, closed without merging