Disable Consul Openshift scenario OpenShiftConsulConfigSourceIT
quarkus-qe/quarkus-test-suite pull request #569
Opened 2022-03-14 10:03 UTC by pjgg

Consul scenario is failing in openshift because of a reported issue that is not merged into Quarkus 2.7.x

2022-03-14 12:16 UTC, rsvoboda requested changes

2022-03-14 12:16 UTC, rsvoboda commented on properties/src/test/java/io/quarkus/qe/properties/consul/OpenShiftConsulConfigSourceIT.java
> +@Disabled
```suggestion
@Disabled("https://github.com/quarkusio/quarkus/issues/24277")
```

2022-03-14 12:16 UTC, rsvoboda commented on properties/src/test/java/io/quarkus/qe/properties/consul/OpenShiftConsulConfigSourceIT.java
> +//TODO https://github.com/quarkusio/quarkus/issues/24277
drop this and use ^^

2022-03-25 08:42 UTC, pjgg commented
The reported issue is already fixed and merged on Quarkus 2.7.5.Final

2022-03-25 08:42 UTC, closed without merging