Add Quarkus test suite PR template
quarkus-qe/quarkus-test-suite pull request #576
Opened 2022-03-21 14:59 UTC by pjgg

### Summary

Add pull request template to Quarkus test suite main branch

### Checklist:
- [X] Commits are well encapsulated and follow [team agreetments](https://gitlab.cee.redhat.com/quarkus-qe/signpost/-/blob/main/pull-requests.md)

2022-03-22 09:40 UTC, rsvoboda requested changes
Same comment as for https://github.com/quarkus-qe/quarkus-test-framework/pull/438#pullrequestreview-916929960

2022-03-22 10:52 UTC, mjurc requested changes

2022-03-22 10:52 UTC, mjurc commented on .github/pull_request_template.md
> +Please delete options that are not relevant.
Please select the relevant options

2022-03-22 10:52 UTC, mjurc commented on .github/pull_request_template.md
> +- [ ] Methods and classes used in PR scenarios are meaningful according to the purpose of this test
I'm not quite sure what this means

2022-03-22 10:52 UTC, mjurc commented on .github/pull_request_template.md
> +- [ ] Commits are well encapsulated and follow [team agreetments](https://gitlab.cee.redhat.com/quarkus-qe/signpost/-/blob/main/pull-requests.md)
I don't really like this for multitude of reasons:

* this is an opensource project, but the doc is closed behind VPN
* we're exposing internal infra 
* we have contributors not in the team

2022-03-22 13:15 UTC, mjurc requested changes

2022-03-22 13:15 UTC, mjurc commented on .github/pull_request_template.md
> +- [ ] Commits are well encapsulated and follow [good practices](https://cbea.ms/git-commit/)
I think the phrase is 'the best practices', right?

2022-03-22 16:04 UTC, merged

2022-03-24 00:16 UTC, mjurc reviewed
I'm leaving a comment here as this is hanging in my review requests.