quarkus-cli should allow you to select which java version to target
quarkus-qe/quarkus-test-suite pull request #584
Opened 2022-03-29 18:50 UTC by pjgg

### Summary

Quarkus-cli should be able to select which java version to target. This PR verifies this behavior

Please select the relevant options.

- [X] New scenario (non-breaking change which adds functionality)

### Checklist:
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-03-30 11:19 UTC, jsmrcka requested changes

2022-03-30 11:19 UTC, jsmrcka commented on quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
> +    private String truncateCurrentJavaVersion() {
The name of this method does not correspond with what it does.

And what is the point here? To use JDK which is not the default in the system?
I don't see why. CLI's `--java` supports `11` and `17` (`11` is default), so why not just try both options, regardless to the system default?

2022-03-30 11:19 UTC, jsmrcka commented on quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
> +        QuarkusCliClient.Result result = app.buildOnJvm();
I think this won't work unless we make sure that `maven-compiler-plugin` uses the same JDK as the one provided by the `--java` param.
Is that even possible? We would need to make sure the JDK is installed, and also specify `JAVA_HOME`.

2022-03-31 05:45 UTC, jsmrcka approved these changes

2022-03-31 08:26 UTC, rsvoboda requested changes

2022-03-31 08:26 UTC, rsvoboda commented on quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
>          } catch (IOException | XmlPullParserException e) {
Also check generated Dockerfile.jvm. This is needed for good OpenShift experience.

2022-03-31 08:26 UTC, rsvoboda commented on quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
> +                    "Unexpected Java version. Java support tool should detect host Java version or use " +
```suggestion
                    "Unexpected Java version defined in maven.compiler.release property of pom.xml. Java support tool should detect host Java version or use " +
```

2022-03-31 12:39 UTC, rsvoboda approved these changes

2022-03-31 12:59 UTC, merged