Migrated messaging apps
quarkus-qe/quarkus-test-suite pull request #8
Opened 2021-04-20 13:14 UTC by Sgitario

| messaging/artemis | messaging/artemis |
| messaging/artemis-jta | messaging/artemis-jta |
| messaging/amqp-reactive | messaging/amqp-reactive |
| messaging/qpid | messaging/qpid |
| messaging/kafka-streams-reactive-messaging | messaging/kafka-streams-reactive-messaging |
| messaging/kafka-avro-reactive-messaging | messaging/kafka-avro-reactive-messaging |

2021-04-23 11:17 UTC, pjgg commented
There is a test error on `messaging-artemis`:

```
Expected: a string containing "10, 20, 30, 40, 50, 60, 70, 80, 90, 100"
  Actual: []
```

Could be a flaky test?

2021-04-23 11:17 UTC, pjgg requested changes
Review test failures

2021-04-23 12:48 UTC, Sgitario commented
> Review test failures

The test failures are caused by a sneaky test that I think I fixed it for all. I need to provide another PR for the old OpenShift TS to fix it there too.

2021-04-26 08:47 UTC, pjgg approved these changes

2021-04-26 08:48 UTC, merged