Fix/ocp4.11
quarkus-qe/quarkus-test-suite pull request #802
Opened 2022-08-24 12:38 UTC by fedinskiy

### Summary

Make TS work on OCP 4.11

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-08-24 12:38 UTC, fedinskiy commented
run tests

2022-08-25 07:42 UTC, jsmrcka commented
run tests

2022-08-26 06:31 UTC, fedinskiy commented
run tests

2022-08-26 14:22 UTC, mjurc approved these changes
LGTM, thank you for the contribution.

2022-08-26 14:24 UTC, mjurc requested changes

2022-08-26 14:24 UTC, mjurc commented on sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftHibernateReactiveMsSQLIT.java
> +import org.junit.jupiter.api.Disabled;
Actually, bad sorting on imports here, see the CI failure.

2022-08-26 14:59 UTC, mjurc approved these changes

2022-08-29 06:49 UTC, fedinskiy commented
`cannot locate openjdk-11` ? Sounds weird. I will rerun OCP tests

2022-08-29 06:49 UTC, fedinskiy commented
run tests

2022-08-30 11:19 UTC, rsvoboda requested changes
Why is the PR targeting 2.7, we should start with main and bulk-backport the necessary fixes to 2.7? cc @pjgg 

I'm not excited about dropping MSSQL coverage. There seems to be workaround with setting security context. We need to see if we can have this done in FW and how much work is it.

2022-09-01 09:17 UTC, rsvoboda approved these changes
There is workaround for MSSQL image trouble, but we need to investigate if that is safe (doesn't need higher privileges) and we can do MSSQL specific adjustment in FW. There is dedicated Trello card for that.

Plan for now is to disable MSSQL OCP tests, Fedor will create similar PR for `main`

2022-09-01 09:18 UTC, merged