Add rest-data-panache + resteasy-reactive module
quarkus-qe/quarkus-test-suite pull request #855
Opened 2022-10-04 17:14 UTC by jsmrcka

### Summary

Based on https://issues.redhat.com/browse/QUARKUS-2390 - Promote quarkus-hibernate-orm-rest-data-panache extension from TP to full support.

Test plan:
https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2390.md

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-10-04 20:52 UTC, jsmrcka commented
Error in OCP JVM  - `Quarkus QE TS: Messaging: Reactive Kafka` (`messaging-modules`) is unrelated.
https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-jvm-ocp-4/11/jdk=openjdk-11,label=RHEL8%20&&%20large,scenario=messaging-modules/consoleFull

2022-10-05 08:12 UTC, fedinskiy requested changes

2022-10-06 08:44 UTC, jsmrcka commented on sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/PanacheRepositoryResourceIT.java
> +    private String getUsersSorted(String sortFieldName) {
Renamed to `sortField`.

2022-10-06 09:40 UTC, fedinskiy approved these changes

2022-10-06 10:12 UTC, merged