Add additional HTTP headers coverage
quarkus-qe/quarkus-test-suite pull request #926
Opened 2022-11-24 12:26 UTC by jsmrcka

### Summary

Tests of additional HTTP headers and additional HTTP headers per path (QUARKUS-2490).
Coverage for both non-reactive and reactive execution + OpenShift.

See also
https://quarkus.io/guides/http-reference#additional-http-headers.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-11-24 13:16 UTC, fedinskiy requested changes

2022-11-24 13:16 UTC, fedinskiy commented on http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HeadersIT.java
> +        final List<String> headerValues = response.extract().headers().getValues(CACHE_CONTROL_HEADER);
This is the only usage of this constant. How about inlining?

2022-11-25 11:37 UTC, jsmrcka commented on http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HeadersIT.java
> +        Assertions.assertTrue(headerValues.stream().noneMatch(matcher::matches));
Replaced with
```java
assertThat(headerValues, not(hasItem(containsString("max-age=31536000"))));
```

2022-11-25 11:43 UTC, fedinskiy approved these changes

2022-11-25 15:15 UTC, merged