Upgrade infinispan to version 14
quarkus-qe/quarkus-test-suite pull request #932
Opened 2022-12-01 16:32 UTC by pjgg

### Summary

Infinispan 14 introduce new config properties. This PR add all this required changes into the test-suite
Reference Doc:
- https://infinispan.org/docs/stable/titles/server/server.html#authentication-mechanisms
- https://infinispan.org/docs/stable/titles/server/server.html#security-realms

Please select the relevant options.

- [X] Dependency update
- [X] Refactoring

### Checklist:
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

2022-12-01 20:34 UTC, michalvavrik requested changes

2022-12-01 20:34 UTC, michalvavrik commented on messaging/infinispan-grpc-kafka/src/main/resources/application.properties
> +quarkus.log.category."org.infinispan".level=DEBUG
I'm not against this, but is that really necessary? Any specific reason, please?

2022-12-01 20:34 UTC, michalvavrik commented on messaging/infinispan-grpc-kafka/README.md
> +keytool -export -alias 1 -file localhost.cer -keystore keystore.jks
` -storepass password`

2022-12-01 20:34 UTC, michalvavrik commented on messaging/infinispan-grpc-kafka/README.md
> +keytool -import -v -trustcacerts -alias 1 -file localhost.cer -keystore truststore.jks
` -storepass password`

2022-12-02 09:23 UTC, pjgg commented on messaging/infinispan-grpc-kafka/README.md
> -##hotrod-client.properties
No, indeed in the previous version wasn't needed, we didn't have a `hotrod-client.properties` on the repository. This readme comment was a leftover from the first version.

2022-12-02 11:53 UTC, michalvavrik approved these changes
lgtm

2022-12-02 13:55 UTC, merged

2022-12-02 14:46 UTC, rsvoboda commented
How does the things look when running against RH Data Grid on OpenShift.

Is the config change needed too for https or the backward compatibility is preserved?